In [4]:
import numpy as np
import pandas as pd

In [62]:
df_into = pd.read_csv('/home/jacs/Documents/DataScience/Personal/song_similarity_audio/TinySOL/TinySOL_metadata.csv')
df_into= df_into[df_into['Needed digital retuning']]
notes = list(df_into['Pitch'].unique())

In [84]:
def hist_sum(freqs, sp, bins, sp_sum):
    min_max_freq = np.arange(0,4000,1)
    interval = int(len(min_max_freq)/bins)
    freq_ranges = [(min(min_max_freq[i*interval:(i+1)*interval]),max(min_max_freq[i*interval:(i+1)*interval])) for i in range(0,bins)]
#    print(freq_ranges)
    for kk in range(0,len(freqs)):
        freq = freqs[kk]
        for rangee in freq_ranges:
            ###### DUDA AQUI
            rangee_string = str(rangee)
            ###############
            ###### DUDA AQUI 2
            if freq in range(int(rangee[0]),int(rangee[1])):
                try:
                    sp_sum[rangee_string] += sp[kk]
                except:
                    sp_sum[rangee_string] = sp[kk]
            else:
                try:
                    sp_sum[rangee_string] += 0
                except:
                    sp_sum[rangee_string] = 0
            ###############
    return sp_sum

In [85]:
df_dumm = pd.read_csv('/home/jacs/Documents/DataScience/Personal/song_similarity/melodic_contour/e7/E7_freq.csv')

sp_sum = {}
for ii in range(0,len(df_dumm)):
    freqos = df_dumm.iloc[ii]['10_freq']
    freqos = freqos.replace('[','').replace(']','').split(', ')
    freqos = [float(freqo) for freqo in freqos]
    spos = df_dumm.iloc[ii]['10_peak']
    spos = spos.replace('[','').replace(']','').split(', ')
    spos = [float(spo) for spo in spos]
    sp_sum = hist_sum(freqos, spos, 40, sp_sum)

In [86]:
df_dumm

,10_freq,10_peak,note_played
0,"[667, 667, 674, 674, 649, 649, 700, 700, 633, ...","[1.0, 1.0, 0.9980174361419819, 0.9980174361419...",E7
1,"[675, 675, 671, 671, 683, 683, 1347, 1347, 661...","[1.0, 1.0, 0.4679950117265357, 0.4679950117265...",E7
2,"[671, 671, 673, 673, 1340, 1340, 1349, 1349, 6...","[1.0, 1.0, 0.3972403184721277, 0.3972403184721...",E7
3,"[675, 675, 669, 669, 673, 673, 1340, 1340, 677...","[1.0, 1.0, 0.623689769928379, 0.62368976992837...",E7
4,"[1339, 1339, 669, 669, 667, 667, 1337, 1337, 1...","[1.0, 1.0, 0.72099297297276, 0.72099297297276,...",E7
...,...,...,...
109,"[2642, 2642, 1166, 1166, 346, 590, 2364, 2364,...","[1.0, 1.0, 0.9658179102090162, 0.9658179102090...",E7
110,"[2214, 2214, 1402, 1402, 420, 1122, 1122, 1760...","[1.0, 1.0, 0.9266194598438101, 0.9266194598438...",E7
111,"[952, 952, 2477, 2477, 535, 1222, 1222, 1678, ...","[1.0, 1.0, 0.9043138860353718, 0.9043138860353...",E7
112,"[973, 973, 452, 2240, 2240, 1822, 1822, 1276, ...","[1.0, 1.0, 0.9633132897931291, 0.9226241517396...",E7
113,"[1304, 1304, 707, 707, 1124, 1124, 900, 900, 3...","[1.0, 1.0, 0.9482873049306089, 0.9482873049306...",E7

In [87]:
sp_sum

{'(0, 99)': 27.614772889176766,
 '(100, 199)': 1.6918303357666793,
 '(200, 299)': 2.4161401351381837,
 '(300, 399)': 2.45564853505329,
 '(400, 499)': 3.914995381474336,
 '(500, 599)': 4.4482566653127895,
 '(600, 699)': 390.6648099266922,
 '(700, 799)': 6.231595037797419,
 '(800, 899)': 2.505676911654306,
 '(900, 999)': 5.553684227669155,
 '(1000, 1099)': 6.03943968650221,
 '(1100, 1199)': 5.513605100281115,
 '(1200, 1299)': 3.4648389737619865,
 '(1300, 1399)': 140.46061526405327,
 '(1400, 1499)': 3.6772048568110596,
 '(1500, 1599)': 1.7327832909550942,
 '(1600, 1699)': 4.2866045981846055,
 '(1700, 1799)': 3.721924964080383,
 '(1800, 1899)': 3.5021417859478094,
 '(1900, 1999)': 4.570415220372292,
 '(2000, 2099)': 10.381058328087356,
 '(2100, 2199)': 0.5028927479027577,
 '(2200, 2299)': 7.608849385748863,
 '(2300, 2399)': 5.152552168148422,
 '(2400, 2499)': 2.642523199169714,
 '(2500, 2599)': 2.420633754131878,
 '(2600, 2699)': 3.6124362230729927,
 '(2700, 2799)': 0,
 '(2800, 2899)': 0,
 '(2900, 2999)': 0,
 '(3000, 3099)': 0,
 '(3100, 3199)': 0,
 '(3200, 3299)': 0,
 '(3300, 3399)': 0,
 '(3400, 3499)': 0,
 '(3500, 3599)': 0,
 '(3600, 3699)': 0,
 '(3700, 3799)': 0,
 '(3800, 3899)': 0,
 '(3900, 3999)': 0}